# Generated by Django 4.2.17 on 2026-06-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.CharField(db_index=True, max_length=150)),
                ('ai_specialization', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('industry', models.CharField(blank=True, default='', max_length=100)),
                ('experience_level', models.CharField(choices=[('Entry', 'Entry Level'), ('Mid', 'Mid Level'), ('Senior', 'Senior Level'), ('Lead', 'Lead / Executive')], db_index=True, max_length=20)),
                ('experience_years', models.IntegerField(default=0)),
                ('salary_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonus_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('education_required', models.CharField(blank=True, default='', max_length=50)),
                ('company_size', models.CharField(blank=True, choices=[('Startup', 'Startup'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Enterprise', 'Enterprise')], default='', max_length=20)),
                ('company_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('work_mode', models.CharField(choices=[('Remote', 'Remote'), ('Onsite', 'On-site'), ('Hybrid', 'Hybrid')], db_index=True, max_length=20)),
                ('weekly_hours', models.DecimalField(decimal_places=1, default=40, max_digits=4)),
                ('year', models.IntegerField(db_index=True, default=2024)),
                ('job_openings', models.IntegerField(default=1)),
                ('skill_demand_score', models.IntegerField(default=0)),
                ('automation_risk', models.IntegerField(default=0)),
                ('job_security_score', models.IntegerField(default=0)),
                ('career_growth_score', models.IntegerField(default=0)),
                ('work_life_balance_score', models.IntegerField(default=0)),
                ('employee_satisfaction', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Job Postings',
                'ordering': ['-salary_usd'],
            },
        ),
    ]
